- name: Demo on Blockinfile
  hosts: all
  tasks:
    - name: demo on adding blocks
      blockinfile:
        path: /home/centos/temporary.conf
        create: yes
        block:
          match user ansible-agent
          password authentication no


