- name: demo on conditions
  hosts: all
  vars:
    x: abc
    action: true
     
  tasks:
   - name: run this when os is centos
     debug:
       msg: hello from centos
     when: ansible_distribution == "CentOS"

   - name: run this when os is Redhat
     debug:
       msg: hello from centos
     when: ansible_distribution == "Redhat" 

   - name: demo on defined - not defined keywords
     debug:
       msg: variable x is defined  

   - name: print me only when action is true
     debug:
       msg: Hi, I was defined with true on action
      when: action      

           