- name: demo on facts
  hosts: all
  tasks:
    - name: printing a fact variable
      debug:
        msg: "{{ansible_distribution}}"
    - name: printing the mac id 
      debug:
        msg: "{{ansible_default_ipv4.macaddress}}"