- name: demo on facts
  hosts: all
  tasks:
    - name: printing a fact variable
      debug:
        msg: "{{ansible_distribution}}"
    - name: printig mac id address
      debug:
        msg: "{{ansible_default_ip4.macaddress}}"   