- name: play1 ## name of the play
  hosts: all
  tasks:
    - name: print hello from play1 ## name of the task
      debug:
        msg: hello from task1 of play1

    - name: print hello from play1 ## name of the task
      debug:
        msg: hello from task2 of play1

- name: play2 ## name of the play
  hosts: all
  tasks:
    - name: print hello from play2 ## name of the play
      debug:
        msg: hello from task1 of play2

    - name: print hello from play2 ## name of the play
      debug:
        msg: hello from task2 of play2              