- name: demo on web app db
  hosts: all
  become: yes
  tasks:
    - name: installing HTTPD webserver
      package:
       name: httpd 
       state: present
    - name:Copying the proxy file
      copy:
        src: proxy.conf
        dest: /etc/httpd/conf.d/proxy.conf   